sudo: required

language: java

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build docker images
      services:
        - docker
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker build --file=distribution/Dockerfile -t cycloneproject/keycloak-mysql .
        - ls -a
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker push cycloneproject/keycloak-mysql;
          fi
    - script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker build --file=distribution/Dockerfile -t cycloneproject/keycloak-mysql:test .
        - ls -a
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker push cycloneproject/keycloak-mysql;
          fi
      services:
        - docker