sudo: required

language: java

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"

services:
  - docker

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build docker images
      before_script:
        - export MAVEN_SKIP_RC=true
      script:
        - export MAVEN_SKIP_RC=true
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker build --file=distribution/Dockerfile -t cycloneproject/keycloak-mysql .
        - mvn install -Pdistribution -DskipTests=true -B -V -q
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker push cycloneproject/keycloak-mysql;
          fi
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt